# Generated by Django 5.1.7 on 2025-04-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('sobrenome', models.TextField(max_length=100)),
                ('ddd', models.TextField(max_length=3)),
                ('telefone', models.TextField(max_length=14)),
                ('email', models.EmailField(max_length=255)),
                ('assunto', models.TextField()),
                ('mensagem', models.TextField(max_length=500)),
            ],
        ),
    ]
